name: CI TalentoTech
on:
  push:
    branches: [ main,develop ]
  pull_request:
    branches: [ main,develop ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.12'
      PIP_CACHE: ~/.cache/pip
      

    steps:
      #1 Checkout the repository
      - name: Checkout codigo
        uses: actions/checkout@v4


      #2 cache de pip
      - name: Cache dependencia
        uses: actions/cache@v4    
        with:
          path: ${{ env.PIP_CACHE }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      #3 Setup Python
      - name: instalar Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      #4 Install dependencies
      - name: Instalar dependencias
        run: pip install -r requirements.txt

      #5 Ejecutar pruebas
      - name: Run Tests 
        run: python3 run_test.py

      #6 Subir reporte de pruebas
      - name: Subir HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: |
              reports/report.html            
              reports/screenshots/**         
              !reports/historial_report/**   

      - name: Subir logs de pruebas
        uses: actions/upload-artifact@v4
        with:
          name: suite-logs
          path: logs/